using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;
using System.Text;
using System.Text.Json.Serialization;
using BasicCommerce.Domain;
using BasicCommerce.Infrastructure;
using CloudinaryDotNet;
using CloudinaryDotNet.Actions;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;

var localEnvFile = FindLocalEnvFile();
if (localEnvFile is not null) LoadDotEnv(localEnvFile);

var builder = WebApplication.CreateBuilder(args);
if (int.TryParse(Environment.GetEnvironmentVariable("PORT"), out var renderPort)) builder.WebHost.UseUrls($"http://0.0.0.0:{renderPort}");
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();
builder.Services.AddProblemDetails();
builder.Services.ConfigureHttpJsonOptions(o => o.SerializerOptions.Converters.Add(new JsonStringEnumConverter()));
builder.Services.AddHealthChecks();
var connection = builder.Configuration.GetConnectionString("Default") ?? Environment.GetEnvironmentVariable("ConnectionStrings__Default");
if (string.IsNullOrWhiteSpace(connection)) throw new InvalidOperationException("ConnectionStrings__Default is required.");
builder.Services.AddDbContext<AppDbContext>(o => o.UseNpgsql(connection));
builder.Services.AddSingleton<IPasswordHasher<User>, PasswordHasher<User>>();
builder.Services.AddSingleton(sp => { var c = builder.Configuration; return new Cloudinary(new Account(c["Cloudinary:CloudName"] ?? Environment.GetEnvironmentVariable("Cloudinary__CloudName") ?? "", c["Cloudinary:ApiKey"] ?? Environment.GetEnvironmentVariable("Cloudinary__ApiKey") ?? "", c["Cloudinary:ApiSecret"] ?? Environment.GetEnvironmentVariable("Cloudinary__ApiSecret") ?? "")); });
var jwtSecret = builder.Configuration["Jwt:Secret"] ?? Environment.GetEnvironmentVariable("Jwt__Secret") ?? throw new InvalidOperationException("Jwt secret missing");
var jwtIssuer = builder.Configuration["Jwt:Issuer"] ?? Environment.GetEnvironmentVariable("Jwt__Issuer") ?? "BasicCommerce.Api";
var jwtAudience = builder.Configuration["Jwt:Audience"] ?? Environment.GetEnvironmentVariable("Jwt__Audience") ?? "BasicCommerce.Frontend";
var tokenMinutes = int.TryParse(builder.Configuration["Jwt:AccessTokenMinutes"] ?? Environment.GetEnvironmentVariable("Jwt__AccessTokenMinutes"), out var tm) ? tm : 60;
builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme).AddJwtBearer(o => o.TokenValidationParameters = new TokenValidationParameters { ValidateIssuer = true, ValidateAudience = true, ValidateLifetime = true, ValidateIssuerSigningKey = true, ValidIssuer = jwtIssuer, ValidAudience = jwtAudience, IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(jwtSecret)), ClockSkew = TimeSpan.FromSeconds(30) });
builder.Services.AddAuthorization(o => o.AddPolicy("Admin", p => p.RequireRole("Admin")));
var origins = (Environment.GetEnvironmentVariable("Cors__AllowedOrigins__0") ?? "http://localhost:5173")
    .Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries)
    .Select(origin => origin.TrimEnd('/'))
    .Distinct(StringComparer.OrdinalIgnoreCase)
    .ToArray();
builder.Services.AddCors(o => o.AddDefaultPolicy(p => p.WithOrigins(origins).AllowAnyHeader().AllowAnyMethod()));
var app = builder.Build();
app.UseExceptionHandler(); app.UseCors(); if (app.Environment.IsDevelopment()) { app.UseSwagger(); app.UseSwaggerUI(); }
app.UseAuthentication(); app.UseAuthorization();
app.MapHealthChecks("/health/live");
app.MapGet("/health/ready", async (AppDbContext db) => await db.Database.CanConnectAsync() ? Results.Ok(new { status = "ready" }) : Results.StatusCode(503));
using (var scope = app.Services.CreateScope())
{
    var db = scope.ServiceProvider.GetRequiredService<AppDbContext>();
    await db.Database.MigrateAsync();
    if (app.Environment.IsDevelopment())
        await SeedAsync(db, scope.ServiceProvider.GetRequiredService<IPasswordHasher<User>>(), builder.Configuration);
}

app.MapPost("/api/auth/register", async (RegisterRequest req, AppDbContext db, IPasswordHasher<User> hasher) => { if (string.IsNullOrWhiteSpace(req.Name) || string.IsNullOrWhiteSpace(req.Email) || req.Password.Length < 8) return Problem(400, "Validation error", "Name, email and an 8+ character password are required.", "VALIDATION_ERROR"); var email = req.Email.Trim().ToLowerInvariant(); if (await db.Users.AnyAsync(x => x.Email == email)) return Problem(409, "Email already registered", "Choose a different email.", "EMAIL_ALREADY_EXISTS"); var u = new User { Name = req.Name.Trim(), Email = email, Phone = req.Phone?.Trim() }; u.PasswordHash = hasher.HashPassword(u, req.Password); db.Users.Add(u); await db.SaveChangesAsync(); return Results.Created("/api/auth/me", UserDto(u)); });
app.MapPost("/api/auth/login", async (LoginRequest req, AppDbContext db, IPasswordHasher<User> hasher) => { var u = await db.Users.SingleOrDefaultAsync(x => x.Email == req.Email.Trim().ToLowerInvariant()); if (u is null || !u.IsActive || hasher.VerifyHashedPassword(u, u.PasswordHash, req.Password) == PasswordVerificationResult.Failed) return Problem(401, "Invalid credentials", "Email or password is incorrect.", "INVALID_CREDENTIALS"); var now = DateTime.UtcNow; var expires = now.AddMinutes(tokenMinutes); var claims = new[] { new Claim(JwtRegisteredClaimNames.Sub, u.Id.ToString()), new Claim(ClaimTypes.NameIdentifier, u.Id.ToString()), new Claim(ClaimTypes.Email, u.Email), new Claim(ClaimTypes.Role, u.Role.ToString()), new Claim(ClaimTypes.Name, u.Name) }; var token = new JwtSecurityToken(jwtIssuer, jwtAudience, claims, now, expires, new SigningCredentials(new SymmetricSecurityKey(Encoding.UTF8.GetBytes(jwtSecret)), SecurityAlgorithms.HmacSha256)); return Results.Ok(new { accessToken = new JwtSecurityTokenHandler().WriteToken(token), expiresAt = expires, user = UserDto(u) }); });
app.MapGet("/api/auth/me", async (ClaimsPrincipal cp, AppDbContext db) => { var u = await CurrentUserAsync(cp, db); return u is null ? Problem(401, "Unauthorized", "Sign in is required.", "INVALID_CREDENTIALS") : Results.Ok(UserDto(u)); }).RequireAuthorization();
app.MapPut("/api/auth/profile", async (ProfileRequest req, ClaimsPrincipal cp, AppDbContext db) => { var u = await CurrentUserAsync(cp, db); if (u is null) return Problem(401, "Unauthorized", "Sign in is required.", "INVALID_CREDENTIALS"); if (string.IsNullOrWhiteSpace(req.Name)) return Problem(400, "Validation error", "Name is required.", "VALIDATION_ERROR"); u.Name = req.Name.Trim(); u.Phone = req.Phone?.Trim(); await db.SaveChangesAsync(); return Results.Ok(UserDto(u)); }).RequireAuthorization();
app.MapPost("/api/auth/change-password", async (ChangePasswordRequest req, ClaimsPrincipal cp, AppDbContext db, IPasswordHasher<User> hasher) => { var u = await CurrentUserAsync(cp, db); if (u is null) return Problem(401, "Unauthorized", "Sign in is required.", "INVALID_CREDENTIALS"); if (hasher.VerifyHashedPassword(u, u.PasswordHash, req.CurrentPassword) == PasswordVerificationResult.Failed || req.NewPassword.Length < 8) return Problem(400, "Password rejected", "Password requirements were not met.", "VALIDATION_ERROR"); u.PasswordHash = hasher.HashPassword(u, req.NewPassword); await db.SaveChangesAsync(); return Results.NoContent(); }).RequireAuthorization();

app.MapGet("/api/categories", async (AppDbContext db) => Results.Ok(await db.Categories.AsNoTracking().Where(x => x.IsActive).OrderBy(x => x.Name).Select(Projections.CategoryDtoExpr()).ToListAsync()));
app.MapGet("/api/admin/categories", async (string? search, AppDbContext db) => Results.Ok(await db.Categories.AsNoTracking().Where(x => string.IsNullOrWhiteSpace(search) || x.Name.ToLower().Contains(search!.ToLower())).OrderBy(x => x.Name).Select(Projections.CategoryDtoExpr()).ToListAsync())).RequireAuthorization("Admin");
app.MapPost("/api/admin/categories", async (CategoryRequest req, AppDbContext db) => { var name = req.Name.Trim(); var slug = Slug(name); if (name.Length < 2 || await db.Categories.AnyAsync(x => x.Slug == slug)) return Problem(409, "Category conflict", "Category name is invalid or already exists.", "CONCURRENCY_CONFLICT"); var c = new Category { Name = name, Slug = slug }; db.Categories.Add(c); await db.SaveChangesAsync(); return Results.Created($"/api/admin/categories/{c.Id}", CategoryDto(c)); }).RequireAuthorization("Admin");
app.MapPut("/api/admin/categories/{id:guid}", async (Guid id, CategoryRequest req, AppDbContext db) => { var c = await db.Categories.FindAsync(id); if (c is null) return Problem(404, "Not found", "Category not found.", "NOT_FOUND"); c.Name = req.Name.Trim(); c.Slug = Slug(c.Name); await db.SaveChangesAsync(); return Results.Ok(CategoryDto(c)); }).RequireAuthorization("Admin");
app.MapPatch("/api/admin/categories/{id:guid}/status", async (Guid id, StatusRequest req, AppDbContext db) => { var c = await db.Categories.FindAsync(id); if (c is null) return Problem(404, "Not found", "Category not found.", "NOT_FOUND"); c.IsActive = req.IsActive; await db.SaveChangesAsync(); return Results.Ok(CategoryDto(c)); }).RequireAuthorization("Admin");

app.MapGet("/api/products", async (int? page, int? pageSize, string? search, Guid? categoryId, string? sort, AppDbContext db) => { var q = db.Products.AsNoTracking().Include(x => x.Category).Where(x => x.IsActive && x.Category.IsActive); if (!string.IsNullOrWhiteSpace(search)) q = q.Where(x => x.Name.ToLower().Contains(search!.ToLower()) || x.Description.ToLower().Contains(search!.ToLower())); if (categoryId.HasValue) q = q.Where(x => x.CategoryId == categoryId); q = sort switch { "price_asc" => q.OrderBy(x => x.Price), "price_desc" => q.OrderByDescending(x => x.Price), "name_asc" => q.OrderBy(x => x.Name), _ => q.OrderByDescending(x => x.CreatedAt) }; var pg = Math.Max(1, page ?? 1); var ps = Math.Clamp(pageSize ?? 12, 1, 100); var total = await q.CountAsync(); return Results.Ok(new { items = await q.Skip((pg - 1) * ps).Take(ps).Select(Projections.ProductListExpr()).ToListAsync(), page = pg, pageSize = ps, totalItems = total, totalPages = (int)Math.Ceiling(total / (double)ps) }); });
app.MapGet("/api/products/{idOrSlug}", async (string idOrSlug, AppDbContext db) => { Product? p = Guid.TryParse(idOrSlug, out var id) ? await db.Products.Include(x => x.Category).SingleOrDefaultAsync(x => x.Id == id) : await db.Products.Include(x => x.Category).SingleOrDefaultAsync(x => x.Slug == idOrSlug); return p is null || !p.IsActive || !p.Category.IsActive ? Problem(404, "Not found", "Product not found.", "NOT_FOUND") : Results.Ok(ProductDto(p)); });
app.MapGet("/api/admin/products", async (int? page, int? pageSize, string? search, AppDbContext db) => { var q = db.Products.AsNoTracking().Include(x => x.Category).Where(x => string.IsNullOrWhiteSpace(search) || x.Name.ToLower().Contains(search!.ToLower())).OrderByDescending(x => x.CreatedAt); var pg = Math.Max(1, page ?? 1); var ps = Math.Clamp(pageSize ?? 20, 1, 100); var total = await q.CountAsync(); return Results.Ok(new { items = await q.Skip((pg - 1) * ps).Take(ps).Select(Projections.ProductListExpr()).ToListAsync(), page = pg, pageSize = ps, totalItems = total, totalPages = (int)Math.Ceiling(total / (double)ps) }); }).RequireAuthorization("Admin");
app.MapPost("/api/admin/products", async (ProductRequest req, AppDbContext db) => await SaveProduct(null, req, db)).RequireAuthorization("Admin");
app.MapPut("/api/admin/products/{id:guid}", async (Guid id, ProductRequest req, AppDbContext db) => await SaveProduct(id, req, db)).RequireAuthorization("Admin");
app.MapPatch("/api/admin/products/{id:guid}/stock", async (Guid id, StockRequest req, AppDbContext db) => { var p = await db.Products.FindAsync(id); if (p is null) return Problem(404, "Not found", "Product not found.", "NOT_FOUND"); if (req.StockQuantity < 0) return Problem(400, "Validation error", "Stock cannot be negative.", "VALIDATION_ERROR"); p.StockQuantity = req.StockQuantity; await db.SaveChangesAsync(); return Results.Ok(ProductDto(p)); }).RequireAuthorization("Admin");
app.MapDelete("/api/admin/products/{id:guid}", async (Guid id, AppDbContext db) => { var p = await db.Products.FindAsync(id); if (p is null) return Problem(404, "Not found", "Product not found.", "NOT_FOUND"); p.IsActive = false; await db.SaveChangesAsync(); return Results.NoContent(); }).RequireAuthorization("Admin");
app.MapPost("/api/admin/media/images", async (HttpRequest request, Cloudinary cloudinary, IConfiguration config) => { if (!request.HasFormContentType) return Problem(400, "Invalid upload", "Multipart form data is required.", "UPLOAD_INVALID_TYPE"); var form = await request.ReadFormAsync(); var file = form.Files.GetFile("file"); if (file is null || file.Length == 0 || file.Length > 5 * 1024 * 1024 || !new[] { "image/jpeg", "image/png", "image/webp" }.Contains(file.ContentType.ToLowerInvariant())) return Problem(400, "Invalid upload", "Use a JPG, PNG or WEBP image up to 5 MB.", "UPLOAD_INVALID_TYPE"); await using var stream = file.OpenReadStream(); var folder = config["Cloudinary:Folder"] ?? Environment.GetEnvironmentVariable("Cloudinary__Folder") ?? "ecommerce-dev"; var result = await cloudinary.UploadAsync(new ImageUploadParams { File = new FileDescription(file.FileName, stream), Folder = folder + "/products", UseFilename = false, UniqueFilename = true }); return result.Error is not null ? Problem(502, "Image upload failed", "Cloudinary rejected the image.", "UPLOAD_INVALID_TYPE") : Results.Created("/api/admin/media/images", new { url = result.SecureUrl?.ToString(), publicId = result.PublicId, width = result.Width, height = result.Height, format = result.Format }); }).RequireAuthorization("Admin");

app.MapGet("/api/cart", async (ClaimsPrincipal cp, AppDbContext db) => { var uid = UserId(cp); var cart = await db.Carts.Include(x => x.Items).ThenInclude(x => x.Product).SingleOrDefaultAsync(x => x.UserId == uid); if (cart is null) return Results.Ok(new { id = Guid.Empty, items = Array.Empty<object>(), itemCount = 0, totalAmount = 0m }); return Results.Ok(new { id = cart.Id, items = cart.Items.Select(i => new { id = i.Id, productId = i.ProductId, productName = i.Product.Name, imageUrl = i.Product.ImageUrl, unitPrice = i.Product.Price, quantity = i.Quantity, availableStock = i.Product.StockQuantity, lineTotal = i.Product.Price * i.Quantity }), itemCount = cart.Items.Sum(i => i.Quantity), totalAmount = cart.Items.Sum(i => i.Product.Price * i.Quantity) }); }).RequireAuthorization();
app.MapPost("/api/cart/items", async (AddCartRequest req, ClaimsPrincipal cp, AppDbContext db) => { if (req.Quantity < 1) return Problem(400, "Validation error", "Quantity must be at least 1.", "VALIDATION_ERROR"); var p = await db.Products.Include(x => x.Category).SingleOrDefaultAsync(x => x.Id == req.ProductId && x.IsActive && x.Category.IsActive); if (p is null) return Problem(404, "Not found", "Product not found.", "NOT_FOUND"); var uid = UserId(cp); var cart = await GetOrCreateCart(uid, db); var item = await db.CartItems.SingleOrDefaultAsync(x => x.CartId == cart.Id && x.ProductId == p.Id); var qty = (item?.Quantity ?? 0) + req.Quantity; if (qty > p.StockQuantity) return Problem(409, "Stock unavailable", "Requested quantity exceeds available stock.", "STOCK_CONFLICT"); if (item is null) db.CartItems.Add(new CartItem { CartId = cart.Id, ProductId = p.Id, Quantity = qty }); else item.Quantity = qty; await db.SaveChangesAsync(); return Results.Ok(new { message = "Added to cart" }); }).RequireAuthorization();
app.MapPatch("/api/cart/items/{id:guid}", async (Guid id, UpdateCartRequest req, ClaimsPrincipal cp, AppDbContext db) => { var uid = UserId(cp); var item = await db.CartItems.Include(x => x.Product).SingleOrDefaultAsync(x => x.Id == id && x.Cart.UserId == uid); if (item is null) return Problem(404, "Not found", "Cart item not found.", "NOT_FOUND"); if (req.Quantity < 1 || req.Quantity > item.Product.StockQuantity) return Problem(409, "Stock unavailable", "Quantity is outside the available stock.", "STOCK_CONFLICT"); item.Quantity = req.Quantity; await db.SaveChangesAsync(); return Results.Ok(new { message = "Cart updated" }); }).RequireAuthorization();
app.MapDelete("/api/cart/items/{id:guid}", async (Guid id, ClaimsPrincipal cp, AppDbContext db) => { var uid = UserId(cp); var item = await db.CartItems.SingleOrDefaultAsync(x => x.Id == id && x.Cart.UserId == uid); if (item is null) return Problem(404, "Not found", "Cart item not found.", "NOT_FOUND"); db.CartItems.Remove(item); await db.SaveChangesAsync(); return Results.NoContent(); }).RequireAuthorization();
app.MapDelete("/api/cart", async (ClaimsPrincipal cp, AppDbContext db) => { var uid = UserId(cp); var items = await db.CartItems.Where(x => x.Cart.UserId == uid).ToListAsync(); db.CartItems.RemoveRange(items); await db.SaveChangesAsync(); return Results.NoContent(); }).RequireAuthorization();

app.MapPost("/api/orders", async (CheckoutRequest req, ClaimsPrincipal cp, AppDbContext db) => { if (req.PaymentMethod != PaymentMethod.CashOnDelivery || string.IsNullOrWhiteSpace(req.CustomerName) || string.IsNullOrWhiteSpace(req.Phone) || string.IsNullOrWhiteSpace(req.ShippingAddress)) return Problem(400, "Validation error", "COD, name, phone and address are required.", "VALIDATION_ERROR"); var uid = UserId(cp); await using var tx = await db.Database.BeginTransactionAsync(System.Data.IsolationLevel.Serializable); var cart = await db.Carts.Include(x => x.Items).ThenInclude(x => x.Product).SingleOrDefaultAsync(x => x.UserId == uid); if (cart is null || cart.Items.Count == 0) return Problem(400, "Cart is empty", "Add an item before checkout.", "EMPTY_CART"); if (cart.Items.Any(i => !i.Product.IsActive || i.Quantity > i.Product.StockQuantity)) return Problem(409, "Stock unavailable", "Cart stock changed. Please review your cart.", "STOCK_CONFLICT"); var order = new Order { UserId = uid, OrderNumber = $"ORD-{DateTime.UtcNow:yyyyMMdd}-{Random.Shared.Next(100000, 999999)}", CustomerName = req.CustomerName.Trim(), Phone = req.Phone.Trim(), ShippingAddress = req.ShippingAddress.Trim(), TotalAmount = cart.Items.Sum(i => i.Product.Price * i.Quantity) }; foreach (var i in cart.Items) { order.Items.Add(new OrderItem { ProductId = i.ProductId, ProductName = i.Product.Name, UnitPrice = i.Product.Price, Quantity = i.Quantity, LineTotal = i.Product.Price * i.Quantity }); i.Product.StockQuantity -= i.Quantity; } db.Orders.Add(order); db.CartItems.RemoveRange(cart.Items); await db.SaveChangesAsync(); await tx.CommitAsync(); return Results.Created($"/api/orders/{order.Id}", new { id = order.Id, orderNumber = order.OrderNumber, status = order.Status.ToString(), paymentMethod = order.PaymentMethod.ToString(), totalAmount = order.TotalAmount, createdAt = order.CreatedAt }); }).RequireAuthorization();
app.MapGet("/api/orders", async (int? page, int? pageSize, ClaimsPrincipal cp, AppDbContext db) => { var uid = UserId(cp); var q = db.Orders.AsNoTracking().Where(x => x.UserId == uid).OrderByDescending(x => x.CreatedAt); var pg = Math.Max(1, page ?? 1); var ps = Math.Clamp(pageSize ?? 10, 1, 50); var total = await q.CountAsync(); return Results.Ok(new { items = await q.Skip((pg - 1) * ps).Take(ps).Select(Projections.OrderSummaryExpr()).ToListAsync(), page = pg, pageSize = ps, totalItems = total, totalPages = (int)Math.Ceiling(total / (double)ps) }); }).RequireAuthorization();
app.MapGet("/api/orders/{id:guid}", async (Guid id, ClaimsPrincipal cp, AppDbContext db) => { var uid = UserId(cp); var o = await db.Orders.AsNoTracking().Include(x => x.Items).SingleOrDefaultAsync(x => x.Id == id && x.UserId == uid); return o is null ? Problem(404, "Not found", "Order not found.", "NOT_FOUND") : Results.Ok(OrderDto(o)); }).RequireAuthorization();
app.MapPost("/api/orders/{id:guid}/cancel", async (Guid id, ClaimsPrincipal cp, AppDbContext db) => await CancelOrder(id, false, db, UserId(cp))).RequireAuthorization();
app.MapGet("/api/admin/orders", async (int? page, int? pageSize, string? status, string? search, AppDbContext db) => { var q = db.Orders.AsNoTracking().Where(x => (string.IsNullOrWhiteSpace(status) || x.Status.ToString() == status) && (string.IsNullOrWhiteSpace(search) || x.OrderNumber.ToLower().Contains(search!.ToLower()) || x.CustomerName.ToLower().Contains(search!.ToLower()))).OrderByDescending(x => x.CreatedAt); var pg = Math.Max(1, page ?? 1); var ps = Math.Clamp(pageSize ?? 20, 1, 100); var total = await q.CountAsync(); return Results.Ok(new { items = await q.Skip((pg - 1) * ps).Take(ps).Select(Projections.OrderSummaryExpr()).ToListAsync(), page = pg, pageSize = ps, totalItems = total, totalPages = (int)Math.Ceiling(total / (double)ps) }); }).RequireAuthorization("Admin");
app.MapGet("/api/admin/orders/{id:guid}", async (Guid id, AppDbContext db) => { var o = await db.Orders.AsNoTracking().Include(x => x.Items).SingleOrDefaultAsync(x => x.Id == id); return o is null ? Problem(404, "Not found", "Order not found.", "NOT_FOUND") : Results.Ok(OrderDto(o)); }).RequireAuthorization("Admin");
app.MapPatch("/api/admin/orders/{id:guid}/status", async (Guid id, StatusValueRequest req, AppDbContext db) => { if (!Enum.TryParse<OrderStatus>(req.Status, true, out var target)) return Problem(400, "Validation error", "Unknown status.", "VALIDATION_ERROR"); var o = await db.Orders.Include(x => x.Items).SingleOrDefaultAsync(x => x.Id == id); if (o is null) return Problem(404, "Not found", "Order not found.", "NOT_FOUND"); if (!Allowed(o.Status, target)) return Problem(409, "Invalid transition", "That status transition is not allowed.", "INVALID_ORDER_TRANSITION"); if (target == OrderStatus.Cancelled) return await CancelOrder(id, true, db, o.UserId); o.Status = target; await db.SaveChangesAsync(); return Results.Ok(OrderDto(o)); }).RequireAuthorization("Admin");
app.MapGet("/api/admin/dashboard/summary", async (AppDbContext db) => Results.Ok(new { totalProducts = await db.Products.CountAsync(), activeProducts = await db.Products.CountAsync(x => x.IsActive), totalOrders = await db.Orders.CountAsync(), pendingOrders = await db.Orders.CountAsync(x => x.Status == OrderStatus.Pending), totalCustomers = await db.Users.CountAsync(x => x.Role == UserRole.Customer) })).RequireAuthorization("Admin");
app.Run();

static IResult Problem(int status, string title, string detail, string code) => Results.Problem(statusCode: status, title: title, detail: detail, extensions: new Dictionary<string, object?> { ["code"] = code });
static Guid UserId(ClaimsPrincipal cp) => Guid.Parse(cp.FindFirstValue(ClaimTypes.NameIdentifier) ?? cp.FindFirstValue(JwtRegisteredClaimNames.Sub)!);
static async Task<User?> CurrentUserAsync(ClaimsPrincipal cp, AppDbContext db) { var uid = UserId(cp); return await db.Users.SingleOrDefaultAsync(x => x.Id == uid); }
static async Task<Cart> GetOrCreateCart(Guid uid, AppDbContext db) { var c = await db.Carts.SingleOrDefaultAsync(x => x.UserId == uid); if (c is not null) return c; c = new Cart { UserId = uid }; db.Carts.Add(c); await db.SaveChangesAsync(); return c; }
static string Slug(string v) => string.Join('-', v.ToLowerInvariant().Split(' ', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries)).Replace("/", "-");
static bool Allowed(OrderStatus from, OrderStatus to) => OrderRules.CanTransition(from, to);
static async Task<IResult> CancelOrder(Guid id, bool admin, AppDbContext db, Guid uid) { await using var tx = await db.Database.BeginTransactionAsync(System.Data.IsolationLevel.Serializable); var o = await db.Orders.Include(x => x.Items).SingleOrDefaultAsync(x => x.Id == id && (admin || x.UserId == uid)); if (o is null) return Problem(404, "Not found", "Order not found.", "NOT_FOUND"); if (!Allowed(o.Status, OrderStatus.Cancelled)) return Problem(409, "Order cannot be cancelled", "That order cannot be cancelled.", "ORDER_NOT_CANCELLABLE"); var ids = o.Items.Select(i => i.ProductId).ToArray(); var products = await db.Products.Where(x => ids.Contains(x.Id)).ToListAsync(); foreach (var item in o.Items) products.Single(x => x.Id == item.ProductId).StockQuantity += item.Quantity; o.Status = OrderStatus.Cancelled; o.CancelledAt = DateTimeOffset.UtcNow; await db.SaveChangesAsync(); await tx.CommitAsync(); return Results.Ok(OrderDto(o)); }
static async Task<IResult> SaveProduct(Guid? id, ProductRequest req, AppDbContext db) { if (string.IsNullOrWhiteSpace(req.Name) || req.Price < 0 || req.StockQuantity < 0) return Problem(400, "Validation error", "Name, nonnegative price and stock are required.", "VALIDATION_ERROR"); if (await db.Categories.FindAsync(req.CategoryId) is null) return Problem(400, "Validation error", "Category not found.", "VALIDATION_ERROR"); var p = id.HasValue ? await db.Products.FindAsync(id.Value) : new Product(); if (id.HasValue && p is null) return Problem(404, "Not found", "Product not found.", "NOT_FOUND"); p!.CategoryId = req.CategoryId; p.Name = req.Name.Trim(); p.Slug = Slug(req.Name); p.Description = req.Description?.Trim() ?? ""; p.Price = req.Price; p.StockQuantity = req.StockQuantity; p.ImageUrl = req.ImageUrl; p.ImagePublicId = req.ImagePublicId; p.ImageAltText = req.ImageAltText; p.IsActive = req.IsActive; if (!id.HasValue) db.Products.Add(p); await db.SaveChangesAsync(); return id.HasValue ? Results.Ok(ProductDto(p)) : Results.Created($"/api/admin/products/{p.Id}", ProductDto(p)); }
static object UserDto(User u) => new { id = u.Id, name = u.Name, email = u.Email, phone = u.Phone, role = u.Role.ToString() };
static object CategoryDto(Category c) => new { id = c.Id, name = c.Name, slug = c.Slug, isActive = c.IsActive };
static object ProductDto(Product p) => new { id = p.Id, categoryId = p.CategoryId, categoryName = p.Category?.Name, name = p.Name, slug = p.Slug, description = p.Description, price = p.Price, stockQuantity = p.StockQuantity, imageUrl = p.ImageUrl, imageAltText = p.ImageAltText, isActive = p.IsActive };
static object OrderDto(Order o) => new { id = o.Id, orderNumber = o.OrderNumber, customerName = o.CustomerName, phone = o.Phone, shippingAddress = o.ShippingAddress, status = o.Status.ToString(), paymentMethod = o.PaymentMethod.ToString(), totalAmount = o.TotalAmount, createdAt = o.CreatedAt, items = o.Items.Select(i => new { id = i.Id, productId = i.ProductId, productName = i.ProductName, unitPrice = i.UnitPrice, quantity = i.Quantity, lineTotal = i.LineTotal }) };
static string? FindLocalEnvFile()
{
    var current = Directory.GetCurrentDirectory();
    foreach (var candidate in new[] { Path.Combine(current, ".env"), Path.Combine(current, "back", ".env") })
        if (File.Exists(candidate)) return candidate;

    for (var directory = new DirectoryInfo(AppContext.BaseDirectory); directory is not null; directory = directory.Parent)
        if (File.Exists(Path.Combine(directory.FullName, "BasicCommerce.sln")))
        {
            var candidate = Path.Combine(directory.FullName, ".env");
            return File.Exists(candidate) ? candidate : null;
        }

    return null;
}
static void LoadDotEnv(string path)
{
    foreach (var rawLine in File.ReadLines(path))
    {
        var line = rawLine.Trim();
        if (line.Length == 0 || line.StartsWith('#')) continue;
        var separator = line.IndexOf('=');
        if (separator <= 0) continue;
        var key = line[..separator].Trim();
        var value = line[(separator + 1)..].Trim();
        if (value.Length >= 2 && ((value[0] == '"' && value[^1] == '"') || (value[0] == '\'' && value[^1] == '\'')))
            value = value[1..^1];
        if (string.IsNullOrWhiteSpace(Environment.GetEnvironmentVariable(key)))
            Environment.SetEnvironmentVariable(key, value);
    }
}
static async Task SeedAsync(AppDbContext db, IPasswordHasher<User> hasher, IConfiguration config) { var email = config["Seed:AdminEmail"] ?? Environment.GetEnvironmentVariable("Seed__AdminEmail"); var password = config["Seed:AdminPassword"] ?? Environment.GetEnvironmentVariable("Seed__AdminPassword"); if (!string.IsNullOrWhiteSpace(email) && !string.IsNullOrWhiteSpace(password) && !await db.Users.AnyAsync(x => x.Email == email.ToLowerInvariant())) { var a = new User { Name = config["Seed:AdminName"] ?? Environment.GetEnvironmentVariable("Seed__AdminName") ?? "Development Admin", Email = email.ToLowerInvariant(), Role = UserRole.Admin }; a.PasswordHash = hasher.HashPassword(a, password); db.Users.Add(a); } foreach (var n in new[] { "Electronics", "Accessories", "Home & Living", "Personal Care" }) { var slug = Slug(n); if (!await db.Categories.AnyAsync(x => x.Slug == slug)) db.Categories.Add(new Category { Name = n, Slug = slug }); } await db.SaveChangesAsync(); if (await db.Products.AnyAsync()) return; var cats = await db.Categories.ToDictionaryAsync(x => x.Slug); foreach (var (name, cat, price, stock) in new[] { ("Wireless Headphones", "electronics", 3499m, 12), ("Portable Bluetooth Speaker", "electronics", 2499m, 8), ("Everyday Backpack", "accessories", 1890m, 15), ("Minimal Wrist Watch", "accessories", 5990m, 3), ("Modern Desk Lamp", "home-&-living", 1290m, 10), ("Ceramic Coffee Mug", "home-&-living", 890m, 20), ("Daily Skin Care Set", "personal-care", 1590m, 7), ("Travel Toiletry Kit", "personal-care", 990m, 0) }) db.Products.Add(new Product { CategoryId = cats[cat].Id, Name = name, Slug = Slug(name), Description = $"Thoughtfully designed {name.ToLowerInvariant()} for everyday use.", Price = price, StockQuantity = stock }); await db.SaveChangesAsync(); }

public record RegisterRequest(string Name, string Email, string Password, string? Phone);
public record LoginRequest(string Email, string Password);
public record ProfileRequest(string Name, string? Phone);
public record ChangePasswordRequest(string CurrentPassword, string NewPassword);
public record CategoryRequest(string Name);
public record StatusRequest(bool IsActive);
public record ProductRequest(Guid CategoryId, string Name, string? Description, decimal Price, int StockQuantity, string? ImageUrl, string? ImagePublicId, string? ImageAltText, bool IsActive = true);
public record StockRequest(int StockQuantity);
public record AddCartRequest(Guid ProductId, int Quantity);
public record UpdateCartRequest(int Quantity);
public record CheckoutRequest(string CustomerName, string Phone, string ShippingAddress, PaymentMethod PaymentMethod);
public record StatusValueRequest(string Status);
